version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: berlusconi
      POSTGRES_PASSWORD: bungabunga

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
