version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
